
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SDbros/RpgCraft_modProject/issues"
displayURL="http://example.com/"
authors="SDbros"
logoFile="rpgcraft.png"
credits="Thanks for this mod goes to me"

[[mods]]
    modId="rpgcraft"
    version="${file.jarVersion}"
    displayName="RpgCraft"
    description='''
    RpgCraft is a work in progress mod that will add rpg like elements to minecraft.
    '''
[[dependencies.rpgcraft]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rpgcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
