modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/SDbros/RpgCraft_modProject/issues"
displayURL="https://minecraft.curseforge.com/projects/biomes-o-plenty"
logoFile="rpg_logo.png"

[[mods]]
    modId="rpgcraft"
    version="${version}"
    displayName="RpgCraft"
	authors="SDbros"
    description='''
    Adds Rpg like elements to Minecraft, very much in early alpha atm.
    '''

[[dependencies.rpgcraft]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"